### ISSUE TITLE
Liteserv crashes with Forestdb option when creating local docs after delete operation

### ISSUE THREAD

**Issue by ashvindersingh** [couchbase/couchbase-lite-ios#1191]
Found on build 1.2.1-10
Sync Gateway: 1.2.1.4
Using Mac OS-X (el-capitan) liteserv client

Steps: 
- Setup and install sync-gateway-tests. https://github.com/couchbaselabs/sync-gateway-tests
- git checkout ios_forestdb_support
- add following environment variables in your shell: 
```
export STORAGE=ForestDB
export SYNCGATE_PATH=/your/path/to/bin/sync_gateway
export LITESERV_PATH=/your/path/to/couchbase-lite-macosx-enterprise_1.2.1-10/LiteServ
```
- Run script from sync-gateway-tests as follows:

```
node tests/cbl-document.js
```

I get the following crash:

```
# docs with bad fields
ok 25 _underscore fields should not be allowed
# delete doc with _delete
ok 26 failed insert hello in http://127.0.0.1:59851/cbl-document1
ok 27 doc missing, got error: {"status":404,"error":"not_found","reason":"missing"}
LiteServ(69243,0x7000008c4000) malloc: *** error for object 0x7fd3930bc800: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug

{ [Error: read ECONNRESET] code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' }
{
  "date": "Thu Mar 31 2016 14:35:11 GMT-0700 (PDT)",
  "process": {
    "pid": 69242,
    "uid": 501,
    "gid": 20,
    "cwd": "/Users/ashvinder/mobile_testing/sync-gateway-tests",
    "execPath": "/usr/local/bin/node",
    "version": "v5.3.0",
    "argv": [
      "/usr/local/bin/node",
      "/Users/ashvinder/mobile_testing/sync-gateway-tests/tests/cbl-document.js"
    ],
    "memoryUsage": {
      "rss": 102129664,
      "heapTotal": 76639264,
      "heapUsed": 54475336
    }
  },
  "os": {
    "loadavg": [
      2.96435546875,
      2.701171875,
      2.52880859375
    ],
    "uptime": 1286008
  },
  "trace": [
    {
      "column": 27,
      "file": "/Users/ashvinder/mobile_testing/sync-gateway-tests/tests/cbl-document.js",
      "function": null,
      "line": 466,
      "method": null,
      "native": false
    },
    {
      "column": 9,
      "file": "/Users/ashvinder/mobile_testing/sync-gateway-tests/node_modules/coax/node_modules/hoax/lib/hoax-core.js",
      "function": "Request._callback",
      "line": 16,
      "method": "_callback",
      "native": false
    },
    {
      "column": 22,
      "file": "/Users/ashvinder/mobile_testing/sync-gateway-tests/node_modules/coax/node_modules/hoax/node_modules/request/main.js",
      "function": "self.callback",
      "line": 122,
      "method": "callback",
      "native": false
    },
    {
      "column": 13,
      "file": "events.js",
      "function": "emitOne",
      "line": 77,
      "method": null,
      "native": false
    },
    {
      "column": 7,
      "file": "events.js",
      "function": "Request.emit",
      "line": 169,
      "method": "emit",
      "native": false
    },
    {
      "column": 10,
      "file": "/Users/ashvinder/mobile_testing/sync-gateway-tests/node_modules/coax/node_modules/hoax/node_modules/request/main.js",
      "function": "ClientRequest.self.clientErrorHandler",
      "line": 225,
      "method": "self.clientErrorHandler",
      "native": false
    },
    {
      "column": 13,
      "file": "events.js",
      "function": "emitOne",
      "line": 77,
      "method": null,
      "native": false
    },
    {
      "column": 7,
      "file": "events.js",
      "function": "ClientRequest.emit",
      "line": 169,
      "method": "emit",
      "native": false
    },
    {
      "column": 9,
      "file": "_http_client.js",
      "function": "Socket.socketErrorListener",
      "line": 265,
      "method": "socketErrorListener",
      "native": false
    },
    {
      "column": 13,
      "file": "events.js",
      "function": "emitOne",
      "line": 77,
      "method": null,
      "native": false
    }
  ],
  "stack": [
    "TypeError: Cannot read property '_id' of undefined",
    "    at /Users/ashvinder/mobile_testing/sync-gateway-tests/tests/cbl-document.js:466:27",
    "    at Request._callback (/Users/ashvinder/mobile_testing/sync-gateway-tests/node_modules/coax/node_modules/hoax/lib/hoax-core.js:16:9)",
    "    at self.callback (/Users/ashvinder/mobile_testing/sync-gateway-tests/node_modules/coax/node_modules/hoax/node_modules/request/main.js:122:22)",
    "    at emitOne (events.js:77:13)",
    "    at Request.emit (events.js:169:7)",
    "    at ClientRequest.self.clientErrorHandler (/Users/ashvinder/mobile_testing/sync-gateway-tests/node_modules/coax/node_modules/hoax/node_modules/request/main.js:225:10)",
    "    at emitOne (events.js:77:13)",
    "    at ClientRequest.emit (events.js:169:7)",
    "    at Socket.socketErrorListener (_http_client.js:265:9)",
    "    at emitOne (events.js:77:13)"
  ],
  "level": "error",
  "message": "uncaughtException: Cannot read property '_id' of undefined",
  "timestamp": "2016-03-31T21:35:11.410Z"
}

```
script line where crash occurs: 
https://github.com/couchbaselabs/sync-gateway-tests/blob/master/tests/cbl-document.js#L444

Possible related with the following fix:
https://github.com/couchbaselabs/cbforest/commit/f0f070af64be62f863ca894120eb6c267c331838

**Comment by ashvindersingh** [comment]
Full script logs: https://gist.github.com/ashvindersingh/45ebe3e8987219109b954c8b3e7a3256

**Comment by snej** [comment]
The evidence from CBL is `malloc: *** error for object 0x7fd3930bc800: pointer being freed was not allocated`. So it's a bad `free()` call. Ashvinder is right, it's possibly a symptom of the bug fixed in that CBForest commit (#1188), but it isn't possible to tell for sure.

**Comment by snej** [comment]
I updated the 1.2.1 branch this morning with that CBForest fix mentioned above, so if this test is re-run on a new 1.2.1 build we can see if the crash reoccurs.

I don't know who will be running these tests, with Ashvinder gone and Seth on vacation this week. My machine isn't set up for them and I haven't run them before.

**Comment by pasin** [comment]
@sethrosetter Can you rerun the test with the current Master?

**Comment by sethrosetter** [comment]
this test passes now.
