### ISSUE TITLE
App Crashing due to Serve crash while switching wifi

### ISSUE THREAD

**Issue by nishantpardamwar** [couchbase/couchbase-lite-ios#1988]
App is crashing while changing wifi

error log

`java.lang.NullPointerException: Attempt to invoke a virtual method on a null object reference
                                                       at Acme.Serve.Serve.serve(Serve.java:877)
                                                       at com.couchbase.lite.listener.LiteServer.serve(LiteServer.java:63)
                                                       at com.couchbase.lite.listener.LiteListener.run(LiteListener.java:90)
                                                       at java.lang.Thread.run(Thread.java:761)`

Steps to reproduce
1) Keep lite listener running in background.
2) Switch wifi network, app crashes (Most of the time).
--------
* Version:   1.4.1
* Client OS: Nougat
* Server:    None (P2P)

**Comment by pasin** [comment]
Please open the issue on https://github.com/couchbase/couchbase-lite-android repo.
