### ISSUE TITLE
Push replication stops with a 404 error

### ISSUE THREAD

**Issue by nl** [couchbase/couchbase-lite-ios#522]
Restarting the replication (or the app) does not fix the issue. I haven't found a way to recover except deleting all remote databases/buckets.

https://gist.github.com/nl/91bb1f51caf5ee7b3355

**Comment by 79144876** [comment]
I have same problem on android,pull error  when i delete the local file(may be some user lost sdcard). i do not know how to fix it?
1.create some documents,(couch.cblite save on my sdcard),and it will auto sync to server.
2.uninstall the app and delete the local cblite file.
3.install app,and login ,and then it can not pull again,i found this error:
```
03-16 13:23:49.490  29769-29831/com.eusoft.recite.en E/Sync﹕ com.couchbase.lite.replicator.ReplicationInternal$4@42eca958 checkSessionAtPath() response: {authentication_handlers=[default, cookie], ok=true, userCtx={channels={0f0665e1-a0fa-4c57-ab00-b4a2bd4cf7d9=9151}, name=0f0665e1-a0fa-4c57-ab00-b4a2bd4cf7d9}}
03-16 13:23:49.500  29769-29832/com.eusoft.recite.en E/Sync﹕ com.couchbase.lite.replicator.ReplicationInternal$4@433b8b08 checkSessionAtPath() response: {authentication_handlers=[default, cookie], ok=true, userCtx={channels={0f0665e1-a0fa-4c57-ab00-b4a2bd4cf7d9=9151}, name=0f0665e1-a0fa-4c57-ab00-b4a2bd4cf7d9}}
03-16 13:23:49.540  29769-29832/com.eusoft.recite.en E/RemoteRequest﹕ Got error status: 404 for http://sync.gateway.frdic.com/admin/reciteen/_local/1d07b7b2b345537243d86ed7b43f4d45f9176379.  Reason: Not Found
03-16 13:25:49.530  29769-29860/com.eusoft.recite.en E/ChangeTracker﹕ com.couchbase.lite.replicator.ChangeTracker@43682e08: Exception in change tracker
    org.codehaus.jackson.JsonParseException: Unexpected character ('<' (code 60)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
            at [Source: org.apache.http.conn.EofSensorInputStream@42f2a348; line: 1, column: 2]
            at org.codehaus.jackson.JsonParser._constructError(JsonParser.java:1432)
            at org.codehaus.jackson.impl.JsonParserMinimalBase._reportError(JsonParserMinimalBase.java:385)
            at org.codehaus.jackson.impl.JsonParserMinimalBase._reportUnexpectedChar(JsonParserMinimalBase.java:306)
            at org.codehaus.jackson.impl.Utf8StreamParser._handleUnexpectedValue(Utf8StreamParser.java:2084)
            at org.codehaus.jackson.impl.Utf8StreamParser._nextTokenNotInObject(Utf8StreamParser.java:600)
            at org.codehaus.jackson.impl.Utf8StreamParser.nextToken(Utf8StreamParser.java:486)
            at org.codehaus.jackson.map.ObjectMapper._initForReading(ObjectMapper.java:2761)
            at org.codehaus.jackson.map.ObjectMapper._readMapAndClose(ObjectMapper.java:2709)
            at org.codehaus.jackson.map.ObjectMapper.readValue(ObjectMapper.java:1900)
            at com.couchbase.lite.replicator.ChangeTracker.run(ChangeTracker.java:331)
            at java.lang.Thread.run(Thread.java:841)
03-16 13:27:49.460  29769-29860/com.eusoft.recite.en E/ChangeTracker﹕ com.couchbase.lite.replicator.ChangeTracker@43682e08: Exception in change tracker
    org.codehaus.jackson.JsonParseException: Unexpected character ('<' (code 60)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
            at [Source: org.apache.http.conn.EofSensorInputStream@42f1d128; line: 1, column: 2]
            at org.codehaus.jackson.JsonParser._constructError(JsonParser.java:1432)
            at org.codehaus.jackson.impl.JsonParserMinimalBase._reportError(JsonParserMinimalBase.java:385)
            at org.codehaus.jackson.impl.JsonParserMinimalBase._reportUnexpectedChar(JsonParserMinimalBase.java:306)
            at org.codehaus.jackson.impl.Utf8StreamParser._handleUnexpectedValue(Utf8StreamParser.java:2084)
            at org.codehaus.jackson.impl.Utf8StreamParser._nextTokenNotInObject(Utf8StreamParser.java:600)
            at org.codehaus.jackson.impl.Utf8StreamParser.nextToken(Utf8StreamParser.java:486)
            at org.codehaus.jackson.map.ObjectMapper._initForReading(ObjectMapper.java:2761)
            at org.codehaus.jackson.map.ObjectMapper._readMapAndClose(ObjectMapper.java:2709)
            at org.codehaus.jackson.map.ObjectMapper.readValue(ObjectMapper.java:1900)
            at com.couchbase.lite.replicator.ChangeTracker.run(ChangeTracker.java:331)
            at java.lang.Thread.run(Thread.java:841)
03-16 13:29:50.500  29769-29860/com.eusoft.recite.en E/ChangeTracker﹕ com.couchbase.lite.replicator.ChangeTracker@43682e08: Exception in change tracker
    org.codehaus.jackson.JsonParseException: Unexpected character ('<' (code 60)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
            at [Source: org.apache.http.conn.EofSensorInputStream@43153d80; line: 1, column: 2]
            at org.codehaus.jackson.JsonParser._constructError(JsonParser.java:1432)
            at org.codehaus.jackson.impl.JsonParserMinimalBase._reportError(JsonParserMinimalBase.java:385)
            at org.codehaus.jackson.impl.JsonParserMinimalBase._reportUnexpectedChar(JsonParserMinimalBase.java:306)
            at org.codehaus.jackson.impl.Utf8StreamParser._handleUnexpectedValue(Utf8StreamParser.java:2084)
            at org.codehaus.jackson.impl.Utf8StreamParser._nextTokenNotInObject(Utf8StreamParser.java:600)
            at org.codehaus.jackson.impl.Utf8StreamParser.nextToken(Utf8StreamParser.java:486)
            at org.codehaus.jackson.map.ObjectMapper._initForReading(ObjectMapper.java:2761)
            at org.codehaus.jackson.map.ObjectMapper._readMapAndClose(ObjectMapper.java:2709)
            at org.codehaus.jackson.map.ObjectMapper.readValue(ObjectMapper.java:1900)
            at com.couchbase.lite.replicator.ChangeTracker.run(ChangeTracker.java:331)
            at java.lang.Thread.run(Thread.java:841)
03-16 13:31:50.520  29769-29860/com.eusoft.recite.en E/ChangeTracker﹕ com.couchbase.lite.replicator.ChangeTracker@43682e08: Exception in change tracker
    org.codehaus.jackson.JsonParseException: Unexpected character ('<' (code 60)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
            at [Source: org.apache.http.conn.EofSensorInputStream@4311f700; line: 1, column: 2]
            at org.codehaus.jackson.JsonParser._constructError(JsonParser.java:1432)
            at org.codehaus.jackson.impl.JsonParserMinimalBase._reportError(JsonParserMinimalBase.java:385)
            at org.codehaus.jackson.impl.JsonParserMinimalBase._reportUnexpectedChar(JsonParserMinimalBase.java:306)
            at org.codehaus.jackson.impl.Utf8StreamParser._handleUnexpectedValue(Utf8StreamParser.java:2084)
            at org.codehaus.jackson.impl.Utf8StreamParser._nextTokenNotInObject(Utf8StreamParser.java:600)
            at org.codehaus.jackson.impl.Utf8StreamParser.nextToken(Utf8StreamParser.java:486)
            at org.codehaus.jackson.map.ObjectMapper._initForReading(ObjectMapper.java:2761)
            at org.codehaus.jackson.map.ObjectMapper._readMapAndClose(ObjectMapper.java:2709)
            at org.codehaus.jackson.map.ObjectMapper.readValue(ObjectMapper.java:1900)
            at com.couchbase.lite.replicator.ChangeTracker.run(ChangeTracker.java:331)
            at java.lang.Thread.run(Thread.java:841)
03-16 13:33:51.540  29769-29860/com.eusoft.recite.en E/ChangeTracker﹕ com.couchbase.lite.replicator.ChangeTracker@43682e08: Exception in change tracker
    org.codehaus.jackson.JsonParseException: Unexpected character ('<' (code 60)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
            at [Source: org.apache.http.conn.EofSensorInputStream@430f4128; line: 1, column: 2]
            at org.codehaus.jackson.JsonParser._constructError(JsonParser.java:1432)
            at org.codehaus.jackson.impl.JsonParserMinimalBase._reportError(JsonParserMinimalBase.java:385)
            at org.codehaus.jackson.impl.JsonParserMinimalBase._reportUnexpectedChar(JsonParserMinimalBase.java:306)
            at org.codehaus.jackson.impl.Utf8StreamParser._handleUnexpectedValue(Utf8StreamParser.java:2084)
            at org.codehaus.jackson.impl.Utf8StreamParser._nextTokenNotInObject(Utf8StreamParser.java:600)
            at org.codehaus.jackson.impl.Utf8StreamParser.nextToken(Utf8StreamParser.java:486)
            at org.codehaus.jackson.map.ObjectMapper._initForReading(ObjectMapper.java:2761)
            at org.codehaus.jackson.map.ObjectMapper._readMapAndClose(ObjectMapper.java:2709)
            at org.codehaus.jackson.map.ObjectMapper.readValue(ObjectMapper.java:1900)
            at com.couchbase.lite.replicator.ChangeTracker.run(ChangeTracker.java:331)
            at java.lang.Thread.run(Thread.java:841)

```

**Comment by pasin** [comment]
For java/android, could you create a new issue at https://github.com/couchbase/couchbase-lite-java-core?

**Comment by 79144876** [comment]
@pasin ok. i have create it. wish you can help me.Thanks.
https://github.com/couchbase/couchbase-lite-java-core/issues/495
